### ISSUE TITLE
Support for NSPersistentCloudKitContainer

### ISSUE THREAD

**Issue by JonnyBeeGod** [johnfairh/TMLPersistentContainer#11]
There is a [new API](https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit) coming out for iOS13 which allows for syncing Core Data to CloudKit:

It looks like [all we have to do is subclass](https://developer.apple.com/documentation/coredata/mirroring_a_core_data_store_with_cloudkit/setting_up_core_data_with_cloudkit) `NSPersistentCloudKitContainer` instead of `NSPersistentContainer`. 

I think it would be great if there would also be an option for using `TMLPersistentContainer` on top of `NSPersistentCloudKitContainer` in case people want to make use of the CloudKit sync while also doing heavyweight migrations.

**Comment by johnfairh** [comment]
Yes this would be good -- looking at it has been on my list since WWDC - has been hectic though.

I was never super-happy with inheriting from `NSPersistentContainer` for exactly this reason but at the time couldn't see how to do a drop-in composition.

**Comment by JonnyBeeGod** [comment]
Hey @johnfairh if you want you can have a look at this https://github.com/JonnyBeeGod/TMLPersistentContainer/pull/1 and let me know your thoughts.

**Comment by johnfairh** [comment]
fixed via #14 in 5.0.0
