### ISSUE TITLE
Interesting problem with this package and the Swift Package Index

### ISSUE THREAD

**Issue by daveverwer** [johnfairh/TMLPersistentContainer#16]
Hey John! I hope it's OK to start an issue to discuss this. I was cleaning up some data in the Swift Package Index today and noticed that TMLPersistentContainer was not showing up in the package search results, even though it's added to the [packages.json](https://github.com/SwiftPackageIndex/PackageList/blob/main/packages.json#L1133) file.

The issue with the manifest is this:

```swift
#if os(Linux)
// No Core Data on Linux
let targets: [Target] = []
#else
let targets: [Target] = [
  .target(name: "TMLPersistentContainer", path: "Sources")]
#endif
```

I can completely see why you've done this, but as we run our package parsing on a Linux docker container (which would be hard to change right now) then we see no valid targets/products when we run `swift package dump-package`.

I'm honestly not sure what the best way to resolve this is. Obviously for the index to pick up the package, we could remove the `#if`, but I can see why you've done this and it makes perfect sense. That said, I don't think we can work around the issue on our side, so we may have to remove the package from the index if we can't figure out a solution.

I thought I'd open an issue in case you or @finestructure have any bright ideas though! Thanks 👍

**Comment by finestructure** [comment]
I wonder if this would solve it:

```

let targets: [Target] = [
#if os(Linux)
// No Core Data on Linux
#else
 .target(name: "TMLPersistentContainer", path: "Sources")
#endif
]
```

**Comment by finestructure** [comment]
Actually, never mind - I thought the whole target block was missing and leading to a parsing error.

But maybe it could be made to work in principle, by pushing the conditional down into a target.

**Comment by johnfairh** [comment]
Well gosh.  I'll take out the `#if` -- this was pretty much the first Swift project I ever wrote and I was probably overthinking the requirements here: I wouldn't do it today.

Thanks for opening this; I'll cut an updated release later this week --- if you need to take the package out of the index then that's fine, I can re-add it afterwards.

**Comment by daveverwer** [comment]
That sounds fantastic, thank you so much @johnfairh!

We can leave the package in no problem as long as there's a fix on the way. We're just tightening up validation and are making sure everything in there is valid right now.

**Comment by daveverwer** [comment]
It just updated on the site too! Thanks so much for fixing this, John


https://swiftpackageindex.com/johnfairh/TMLPersistentContainer

**Comment by johnfairh** [comment]
Great - thanks Dave
